# Generated by Django 3.1.3 on 2021-03-20 15:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=20)),
                ('last_name', models.CharField(help_text='Enter your name', max_length=50, null=True, verbose_name='name')),
                ('email', models.EmailField(help_text='Enter your email', max_length=40, null=True, verbose_name='Email')),
                ('date_creation_account', models.DateTimeField(auto_now_add=True)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('state_acount', models.CharField(default='actif', max_length=75, verbose_name='state account')),
                ('validty_acount', models.CharField(default='valid', max_length=75, verbose_name='validity account')),
                ('num_CNI', models.IntegerField(null=True, verbose_name='number CNI')),
                ('type_account', models.CharField(choices=[('standard', 'standard'), ('premium', 'premium'), ('pro', 'pro'), ('vip', 'vip')], default='standard', max_length=25)),
                ('type_account_certifie', models.CharField(choices=[('certified', 'certified'), ('non-certified', 'non-certified')], default='non-certified', max_length=25)),
                ('number_of_publication_announce', models.IntegerField(default=2, verbose_name='number publication')),
            ],
            options={
                'ordering': ['type_account'],
            },
        ),
        migrations.CreateModel(
            name='AnnounceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_category', models.CharField(max_length=15, verbose_name='category user')),
                ('civility', models.CharField(max_length=15, verbose_name='Civility')),
                ('category', models.CharField(max_length=75, verbose_name='Category')),
                ('city', models.CharField(help_text='Douala, yaounde,...', max_length=25, verbose_name='City')),
                ('region', models.CharField(help_text='Entrer the region', max_length=40, verbose_name='Region')),
                ('available_time_work', models.CharField(max_length=15, verbose_name='Time of work')),
                ('disponibility_periode_work', models.CharField(max_length=25, verbose_name='Period of work')),
                ('competence', models.TextField(default='je suis capable de:', help_text='Describe your expertise', max_length=100, verbose_name='Describe your competences')),
                #('picture_announce', models.ImageField(blank=True, help_text='Enter your profile picture (Optional)', null=True, upload_to='imgProfil/%Y/%m/%d', verbose_name='Picture announce')),
                ('picture_announce', cloudinary.models.CloudinaryField(blank=True, help_text='Enter your profile picture (Optional)', max_length=255, null=True, verbose_name='image'),
                ('first_name', models.CharField(help_text='Enter your First name', max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(help_text='Enter your name', max_length=30, verbose_name='name')),
                ('email', models.EmailField(help_text='Enter your email', max_length=50, verbose_name='Email')),
                ('mobile_phone', models.CharField(max_length=27, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(237)', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Phone')),
                ('number_of_vote', models.IntegerField(default=0)),
                ('note', models.IntegerField(default=0)),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='publication date')),
                ('type_announce', models.CharField(choices=[('standard', 'standard'), ('premium', 'premium'), ('pro', 'pro'), ('vip', 'vip')], default='standard', max_length=25)),
                ('customermodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermodel', to='jebouloapp.customermodel')),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
    ]
