# Generated by Django 3.1.3 on 2021-03-03 11:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jebouloapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnounceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_category', models.CharField(max_length=15, verbose_name='category user')),
                ('civility', models.CharField(max_length=15, verbose_name='Civility')),
                ('category', models.CharField(max_length=75, verbose_name='Category')),
                ('city', models.CharField(help_text='Douala, yaounde,...', max_length=25, verbose_name='City')),
                ('region', models.CharField(help_text='Entrer the region', max_length=40, verbose_name='Region')),
                ('available_time_work', models.CharField(max_length=15, verbose_name='Time of work')),
                ('disponibility_periode_work', models.CharField(max_length=25, verbose_name='Period of work')),
                ('competence', models.TextField(default='je suis capable de:', help_text='Describe your expertise', max_length=100, verbose_name='Describe your competences')),
                ('picture_announce', models.ImageField(blank=True, help_text='Enter your profile picture (Optional)', null=True, upload_to='imgProfil/%Y/%m/%d', verbose_name='Picture announce')),
                ('first_name', models.CharField(help_text='Enter your First name', max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(help_text='Enter your name', max_length=30, verbose_name='name')),
                ('email', models.EmailField(help_text='Enter your email', max_length=50, verbose_name='Email')),
                ('mobile_phone', models.CharField(blank=True, max_length=27, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(237)', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Phone')),
                ('number_of_vote', models.IntegerField(default=0)),
                ('note', models.IntegerField(default=0)),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='publication date')),
                ('type_announce', models.CharField(choices=[('sponsorise', 'sponsorise'), ('standard', 'standard')], default='standard', max_length=25)),
                ('customermodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jebouloapp.customermodel')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
