# Generated by Django 3.1.3 on 2021-03-06 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jebouloapp', '0002_announcemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='current_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customermodel',
            name='date_creation_account',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customermodel',
            name='email',
            field=models.EmailField(help_text='Enter your email', max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='last_name',
            field=models.CharField(help_text='Enter your name', max_length=30, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='num_CNI',
            field=models.IntegerField(null=True, verbose_name='number CNI'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='number_of_publication_competence',
            field=models.IntegerField(default=0, verbose_name='number publication'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='state_acount',
            field=models.CharField(default='actif', max_length=75, verbose_name='state account'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='type_account',
            field=models.CharField(choices=[('standard', 'standard'), ('premium', 'premium'), ('pro', 'pro'), ('vip', 'vip')], default='standard', max_length=25),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='type_account_certifie',
            field=models.CharField(choices=[('certified', 'certified'), ('non-certified', 'non-certified')], default='non-certified', max_length=25),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='validty_acount',
            field=models.CharField(default='valid', max_length=75, verbose_name='validity account'),
        ),
    ]
