# Generated by Django 3.1.3 on 2021-03-30 14:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jebouloapp', '0003_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcemodel',
            name='picture_announce',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Enter your profile picture (Optional)', max_length=255, null=True, verbose_name='image'),
        ),
    ]
