# Generated by Django 3.1.3 on 2021-06-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebouloapp', '0004_auto_20210330_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='email',
            field=models.EmailField(default='provision@jeboulo.com', help_text='Enter your email', max_length=40, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='last_name',
            field=models.CharField(default='a remplir si certification de compte', help_text='Enter your name', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='validty_acount',
            field=models.CharField(default='non-sponsorise', max_length=75, verbose_name='validity account'),
        ),
    ]
