# Generated by Django 3.1.3 on 2021-06-09 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebouloapp', '0005_auto_20210608_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcemodel',
            name='mobile_phone',
            field=models.CharField(max_length=27, validators=[django.core.validators.RegexValidator(message='Enter a valid  mobile phone number', regex='^(6\\d{8})|(6\\d{2}\\s\\d{2}\\s\\d{2}\\s\\d{2})|(\\+2376\\d{8})|(\\+237\\s*6\\d{8})|(00237\\d{9})|(00237\\s*6\\d{8})$')], verbose_name='Phone'),
        ),
    ]
