# Generated by Django 3.1.3 on 2021-03-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebouloapp', '0005_auto_20210308_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermodel',
            options={'ordering': ['type_account']},
        ),
        migrations.AlterField(
            model_name='announcemodel',
            name='type_announce',
            field=models.CharField(choices=[('standard', 'standard'), ('premium', 'premium'), ('pro', 'pro'), ('vip', 'vip')], default='standard', max_length=25),
        ),
    ]
