# Generated by Django 3.1.3 on 2021-07-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jebouloapp', '0006_auto_20210609_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcemodel',
            old_name='number_of_vote',
            new_name='number_of_votes',
        ),
    ]
