# Generated by Django 3.1.3 on 2021-03-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jebouloapp', '0006_auto_20210308_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcemodel',
            options={'ordering': ['publication_date']},
        ),
    ]
